config/routes.rb
Rails.application.routes.draw do

  resources :updates
  root 'homepage#homepage'
  #devise_for :users

  get 'test1' => 'user_setup#test1', as: :test1
  get 'test2' => 'user_setup#test2', as: :test2
  post 'cheat_log_in' => 'myusers#cheat_log_in', as: :cheat_log_in
  get 'reset_to_two_users'=> 'user_setup#reset_to_two_users', as: :reset_to_two_users
  get 'add_jobs_and_tasks'=> 'user_setup#add_jobs_and_tasks', as: :add_jobs_and_tasks

  get 'set_up_clients'=> 'user_setup#set_up_clients', as: :set_up_clients

  get 'hide_jobs'=> 'homepage#hide_jobs', as: :hide_jobs
  post 'hide_selected_jobs'=> 'homepage#hide_selected_jobs', as: :hide_selected_jobs
  post 'unhide_selected_jobs'=> 'homepage#unhide_selected_jobs', as: :unhide_selected_jobs
  get 'order_jobs_tasks'=> 'homepage#order_jobs_tasks', as: :order_jobs_tasks

  get 'hide_tasks'=> 'homepage#hide_tasks', as: :hide_tasks
  post 'hide_selected_tasks'=> 'homepage#hide_selected_tasks', as: :hide_selected_tasks
  post 'unhide_selected_tasks'=> 'homepage#unhide_selected_tasks', as: :unhide_selected_tasks

  get 'task_log/.:id'=> 'tasks#task_log', as: :task_log

  get 'new_user' => 'myusers#new_user' , as:  :new_user

  get 'tasks/message_forum/.:id' => 'tasks#message_forum', as: :tasks_message_forum
  get 'jobs/message_forum/.:id' => 'jobs#message_forum', as: :jobs_message_forum
  post 'task_summons_email/.:id' => 'tasks#summons_email', as: :task_summons_email
  post 'job_summons_email/.:id' => 'jobs#summons_email', as: :job_summons_email
  get 'tasks/summons_landing/.:id' => 'tasks#summons_landing', as: :summons_landing

  post 'jobs_selection' => 'homepage#jobs_include', as: :homepage_jobs_include
  post 'tasks_selection' => 'homepage#tasks_include', as: :homepage_tasks_include

  post 'amend_comments_for_update/.:id' => 'updates#amend_comments_for_update', as: :amend_comments_for_update
  post 'amend_progress_for_update/.:id' => 'updates#amend_progress_for_update', as: :amend_progress_for_update
  post 'amend_comments_for_log/.:id' => 'tasks#amend_comments_for_log', as: :amend_comments_for_log

  #get 'myusers.:id' => 'user_setup#new_user_resend_email'
  #post 'myusers' => 'user_setup#new_user_details'
  #patch 'myusers.:id', :to => 'user_setup#new_user_confirm_details', :as => :myuser

  get 'myuser/confirmation' => 'myusers#new_user_confirmation'
  get 'myuser/invited_user_show/.:id' => 'myusers#invited_user_show', as: :invited_user_show
  patch 'myuser/update_invited_myuser/.:id' => 'myusers#update_invited_user', as: :update_invited_user
  patch 'myuser/myuser_amend/.:id' => 'myusers#myuser_amend', as: :myuser_amend
  #patch 'myuser/update_user/.:id' => 'myusers#update_user', as: :update_user

  post 'myuser/user_invite_return/.:id' => 'myusers#user_invite_return', as: :user_invite_return
  post 'myuser/confirm_for_new_admin_user' => 'myusers#confirm_for_new_admin_user', as: :confirm_for_new_admin_user

  post 'myusers/search' => 'myusers#search', as:  :myusers_search

  get 'login' => 'myusers#login', as:  :login
  post 'login_submit' => 'myusers#login_submit', as:  :login_submit
  delete 'logout' => 'myusers#logout', as: :logout

  #get 'jobs.:clientid' => 'jobs#index_for_client'
  #get 'jobs/new.:clientid' => 'jobs#new'
  post 'clients/client_users/.:id', to:  "clients#client_users" , as:  :client_users
  post 'clients/search', to:  "clients#search" , as:  :clients_search

  get 'clients/show_with_all_fes/.:id', to:  "clients#show_with_all_fes" , as:  :show_with_all_fes


  get 'client/newcontact/.:id', to:  "contacts#new_contact_for_client" , as:  :new_contact_for_client
  get 'client/newjob/.:id', to:  "jobs#new_job_for_client" , as:  :new_job_for_client
  post 'upload_user_file', to:  "myusers#upload_user_file" , as:  :upload_user_file
  post 'import_users', to:  "myusers#import_users" , as:  :import_users
  get 'edit_temp_user/.:id', to:  "myusers#edit_temp_user" , as:  :edit_temp_user
  post 'temp_user/.:id', to:  "myusers#update_temp_user" , as:  :temp_user
  get 'list_temp_users', to:  "myusers#list_temp_users" , as:  :list_temp_users
  delete 'delete_selected_users', to:  "myusers#delete_selected_users" , as:  :delete_selected_users

  get 'job/newtask/.:jobid', to:  "tasks#new_task_for_job" , as:  :new_task_for_job

  get 'job/amendteam/.:id', to:  "jobs#amend_team" , as:  :job_amend_team
  post 'job/addusers/.:jobid', to:  "jobs#add_users" , as:  :job_add_user
  post 'job/removeusers/.:jobid', to:  "jobs#remove_users" , as:  :job_remove_user
  post 'task/addusers/.:id', to:  "tasks#add_users" , as:  :task_add_user
  post 'task/removeusers/.:id', to:  "tasks#remove_users" , as:  :task_remove_user

  post 'job/timing/.:id', to:  "jobs#timing" , as:  :job_timing
  get 'job/today/.:id', to:  "jobs#today" , as:  :job_today
  get 'job/now/.:id', to:  "jobs#now" , as:  :job_now

  get 'update_reminder/new_for_task/.:taskid', to:  "update_reminders#new_for_task" , as:  :update_reminder_new_for_task
  get 'update_reminder/new_for_schedule/.:scheduleid', to:  "update_reminders#new_for_schedule" , as:  :update_reminder_new_for_schedule

  post '/update_reminders/:id', to: "update_reminders#update", as: :update_reminder_update
  post '/update_reminders_and_return/:id', to: "update_reminders#update_and_return", as: :update_reminder_update_and_return

  post 'update_reminder/delete_from_schedule/.:id', to:  "reminder_schedules#delete_reminder" , as:  :delete_reminder_from_schedule
  get 'update_reminder/delete_from_task/.:id', to:  "tasks#delete_reminder" , as:  :delete_reminder_from_task

  post 'template/delete/.:id', to:  "templates#delete_task" , as:  :delete_task_from_template

  get 'tasks/new_task_for_job/.:jobid', to:  "tasks#new_task_for_job" , as:  :task_new_for_job
  get 'tasks/new_task_for_template/.:templateid', to:  "tasks#new_task_for_template" , as:  :task_new_for_template

  post 'task/linked_flag/.:id', to:  "tasks#linked" , as:  :task_linked
  post 'task/timing/.:id', to:  "tasks#timing" , as:  :task_timing
  get 'task/.:id/edit1', to:  "tasks#edit1" , as:  :edit1_task
  post 'task/progress/.:id', to:  "tasks#progress" , as:  :task_update_progress
  post 'task/reminders_completed/.:id', to:  "tasks#reminders_completed" , as:  :task_reminders_completed
  get 'job/delete_task/.:taskid', to:  "jobs#delete_task" , as:  :job_delete_task
  get 'client/delete_job/.:jobid', to:  "clients#delete_job" , as:  :client_delete_job

  post 'job/import_template/.:id', to:  "jobs#import_template" , as:  :jobs_import_template
  get 'job/delete_all_tasks/.:id', to:  "jobs#delete_all_tasks" , as:  :jobs_delete_all_tasks
  post 'task/import_schedule/.:id', to:  "tasks#import_schedule" , as:  :tasks_import_schedule

  post 'update/progress/.:taskid', to:  "updates#update_progress" , as:  :update_progress
  get 'update/new_for_task/.:taskid', to:  "updates#new_for_task" , as:  :update_new_for_task

  get 'update/list_updates_for_task/.:taskid', to:  "updates#list_updates_for_task" , as:  :list_updates_for_task
  #get 'clients' => 'jobs#index_for_client'

  post 'action_update' => 'tasks#action_update', as: :action_update
  post 'action/.:message_id' => 'tasks#action', as: :action
  post 'action_delete/.:action_id' => 'tasks#action_delete', as: :action_delete


  get 'cannot_access' => 'general#cannot_access', as: :cannot_access


    resources :clients
  resources :jobs
  resources :myusers
  resources :templates
  resources :reminder_schedules
  resources :update_reminders
  resources :tasks
  resources :contacts

  #devise_scope :user do
   # get 'users/confirmation' => 'users/registrations#email_confirm'
   # post 'users/email_conf/:userid' => 'users/registrations#email_sign_in'
   # patch 'users/email_conf/:userid' => 'users/registrations#email_sign_in'
  #end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => "/cable"
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def homepage
    @tasks=[]
    @myuser = logged_in_user_helper

    if !@myuser.blank?
      @tasks=@myuser.tasks
    end

    # require "browser/aliases"
    #
    # Browser::Base.include(Browser::Aliases)
    #
    # @browser = Browser.new("Some user agent")
    #
    # if @browser.mobile?
    #   render "mobile_homepage"
    # end

    # if browser.device.mobile? or true
    #   if @myuser or true
    #
    #     render "mobile/login", layout: "mobile"
    #   end
    # end


  end

  def tasks_include
    if logged_in_user_helper

      myuser =  Myuser.find(logged_in_user_helper.id)
      myuser.show_tasks_by_client = ( params[:tasks_include_clients] == "1" )
      myuser.show_tasks_by_job = ( params[:tasks_include_jobs] == "1" )
      myuser.show_tasks_by_task = ( params[:tasks_include_tasks] == "1" )
      myuser.save

    end
    redirect_to root_path

  end

  def jobs_include
    if logged_in_user_helper

      myuser =  Myuser.find(logged_in_user_helper.id)
      myuser.show_jobs_by_client = ( params[:jobs_include_clients] == "1" )
      myuser.show_jobs_by_job = ( params[:jobs_include_jobs] == "1" )
      myuser.save

    end

    redirect_to root_path
  end

  def hide_jobs
  end

  def hide_selected_jobs
    logged_in_user_helper.jobs_for_myuser.each do |job|
      if params["hide" + job.id.to_s]=="1"
        Hide.create(:myuser_id => logged_in_user_helper.id , :element => "job" + job.id.to_s)
      end
    end
    redirect_to root_path
  end

  def unhide_selected_jobs
    Hide.where(:myuser_id => logged_in_user_helper.id).each do |hide|
      if hide.element[0,3] == "job"
        if params["unhide" + hide.element.sub("job","")]=="1"
          hide.delete
        end
      end
    end
    redirect_to root_path
  end
  def hide_tasks
  end

  def hide_selected_tasks

    logged_in_user_helper.tasks_for_myuser.each do |task|
      if params["hide" + task.id.to_s] =="1"
        Hide.create(:myuser_id => logged_in_user_helper.id , :element => "task" + task.id.to_s)
      end
    end
    redirect_to root_path
  end

  def unhide_selected_tasks

    Hide.where(:myuser_id => logged_in_user_helper.id).each do |hide|
      if hide.element[0,4] == "task"
        if params["unhide" + hide.element.sub("task","")] == "1"
          hide.delete
        end
      end
    end
    redirect_to root_path
  end

  def order_jobs_tasks

    myuser = Myuser.find(logged_in_user_helper.id)

    if params[:task_job]=="t"
      if myuser.order_tasks_field == params[:field]
        myuser.order_tasks_field = params[:field] + "_reverse"
      else
        myuser.order_tasks_field = params[:field]
      end
      myuser.save
    elsif params[:task_job]=="j"
      if myuser.order_jobs_field == params[:field]
        myuser.order_jobs_field = params[:field] + "_reverse"
      else
        myuser.order_jobs_field = params[:field]
      end
      myuser.save
    end

    if params[:homepage_hidepage] == "task_hide"
      redirect_to hide_tasks_path
    elsif params[:homepage_hidepage] == "job_hide"
      redirect_to hide_jobs_path
    else
      redirect_to root_path
    end
  end

end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/Duplicate_email.html.erb
Duplicate email

Deleting existing entry and resending email to user.

app/views/homepage/homepage.html.erb
<%= javascript_include_tag 'homepage.js' %>

<% if @myuser %>
  <script type="text/javascript">

    window.onload = function() {

        var tasks_progress;
        tasks_progress = <%= @myuser.task_update_array %>

        tasks_progress.forEach (function(task) {
          var c = document.getElementById("myCanvas" + task["task"]);
          var ctx = c.getContext("2d");
          ctx.lineWidth = "0";
          ctx.fillStyle = "red";
          ctx.fillRect(0 , c.height * 0.05 , c.width * task["exp_prog"], c.height * 0.4);

          ctx.fillStyle = "green";
          ctx.fillRect(  0, c.height * 0.55, c.width * task["act_prog"], c.height * 0.4);

        })

      }
  </script>
<% end %>
<br/>
<% if Myuser.count==0 %>
  <table align="center" style="background-color: lightblue; border-style: solid; border-width: 5px;" width="25%" height="50">
    <tr>
      <td align="center">
        <%= link_to('Create first user', new_user_path) %>
      </td>
    </tr>
  </table>
<% elsif logged_in_user_helper %>
 <% if logged_in_user_helper.is_admin? %>
    <table align="center" style="background-color: lightblue; border-style: solid; border-width: 5px;" width="70%" height="50">
      <col width="25%">
      <col width="25%">
      <col width="25%">
      <col width="25%">
      <tr>
        <td align="center">
          <div class="dropdown" style="text-decoration: underline;">
            Hide
            <div class="dropdown-content">
              <%= link_to('Hide updates', root_path) %>
              <%= link_to('Hide forums', root_path) %>
              <%= link_to('Hide jobs', hide_jobs_path) %>
              <%= link_to('Hide tasks', hide_tasks_path) %>
              <%= link_to('Hide clients', root_path) %>
            </div>
          </div>
        </td>
        <td align="center">
          <div class="dropdown">
            <%= link_to('Users', myusers_path, class: "dropbtn") %>
            <div class="dropdown-content">
              <%= link_to('Users', myusers_path) %>
              <%= link_to('Add user', new_user_path) %>
            </div>
          </div>
        </td>
        <td align="center">
          <div class="dropdown">
            <%= link_to('Clients', clients_path, class: "dropbtn") %>
            <div class="dropdown-content">
              <%= link_to('Clients', clients_path) %>
              <%= link_to('New client', clients_path) %>
            </div>
          </div>
        </td>
        <td align="center">
          <div class="dropdown" style="text-decoration: underline;">
            Templates
            <div class="dropdown-content">
              <%= link_to('Job templates', templates_path) %>
              <%= link_to('Update schedules', reminder_schedules_path) %>
            </div>
          </div>
        </td>
      </tr>
    </table>
  <% end %>
<% else %>
  <table align="center" style="background-color: lightblue; border-style: solid; border-width: 5px;" width="25%" height="50">
    <tr>
      <td align="center">
        <%= link_to("Log in", login_path )  %>
      </td>
    </tr>
  </table>
<% end %>

<table>
  <col width="50%"/>
  <col width="50%"/>
  <tr>
    <td>
      <div class="select_box_wrapper" style="margin-top: 4px; background-color: yellow; ">
        <span style="font-weight: bold">Your updates</span>

        <div class="select_box_list">
          <table>
            <col width="20%"/>
            <col width="22%"/>
            <col width="22%"/>
            <col width="36%"/>

            <tr style="font-weight: bold">
              <td>
                Client
              </td>
              <td>
                Job
              </td>

              <td>
                Task
              </td>
              <td>
                Due date
              </td>
            </tr>

            <% if @myuser  %>
              <% @myuser.updates_for_myuser.each do |reminder| %>
              <tr>
                <td>
                  <%= link_to reminder[:reminder].task.job.client.name, edit_client_path(reminder[:reminder].task.job.client) %>
                </td>
                <td>
                  <%= link_to reminder[:reminder].task.job.name, edit_job_path(reminder[:reminder].task.job) %>
                </td>
                <td>
                  <%= link_to reminder[:reminder].task.name, edit_task_path(reminder[:reminder].task) %>
                </td>
                <td>
                  <% if reminder[:date] + reminder[:reminder].due_period < DateTime.now %>
                  <span style="color: red"><%= reminder[:date].to_s(:date_time_at) %> <span style="font-size: 8pt">OVERDUE</span></span>
                  <% elsif reminder[:date] < DateTime.now %>
                  <span style="color: blue"><%= reminder[:date].to_s(:date_time_at) %> <span style="font-size: 8pt">DUE</span></span>
                  <% else %>
                    <%= reminder[:date].to_s(:date_time_at) %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            <% end %>
          </table>
        </div>
      </div>

      <div class="select_box_wrapper" style="margin-top: 4px; background-color: pink; ">
        <span style="font-weight: bold">Your message forums</span>

        <div class="select_box_list">
          <table>
            <col width=75%>
            <col width=25%>
            <tr style="font-weight: bold">
              <td>Forum</td>
              <td>Last message</td>
            </tr>

           <% if @myuser  %>
             <% @myuser.message_forums.each do |message| %>
             <tr>
               <td>
                <% if message.message_forum_type == "task" %>
                  <span style="color: green"> Task forum</span>

                  <a href="#" onclick="window.open('<%= tasks_message_forum_path(message.task)%>', 'MsgWindow', 'width=400,height=500,left=400,top=100,location=0,status=0,titlebar=0,toolbar=0,menu=0');" ><%= message.message_forum_name_stg %></a>
                <% elsif message.message_forum_type == "job" %>
                  <span style="color: red">Job forum</span>
                  <a href="#" onclick="window.open('<%= jobs_message_forum_path(message.job)%>', 'MsgWindow', 'width=400,height=500,left=400,top=100,location=0,status=0,titlebar=0,toolbar=0,menu=0');" ><%= message.message_forum_name_stg %></a>
                <% end %>
                </td>

                <td>
                  <%= message.time_date_stg %>
                </td>
                </tr>

             <% end %>
           <% end %>
           </table>

        </div>
      </div>




    </td>
    <td>

      <div class="select_box_wrapper" style="height: 174px; margin-top: 4px; background-color: lightgreen; ">
        <table>
          <col width="31%">
          <col width="30%">
          <col width="13%">
          <col width="13%">
          <col width="13%">
          <tr>
            <td>
              <span style="font-weight: bold">Your jobs</span>
            </td>
            <td>
              Include if associated by:
            </td>
            <%= form_tag homepage_jobs_include_path,  :id => 'jobs_include' do %>
              <% if @myuser %>
                <td>
                  Clients <%= check_box_tag 'jobs_include_clients', 1, @myuser.show_jobs_by_client, onchange: "jobs_include.submit()" %>
                </td>
                <td>
                  Jobs <%= check_box_tag 'jobs_include_jobs', 1, @myuser.show_jobs_by_job, onchange: "jobs_include.submit()" %>
                </td>
                <td>
                </td>
              <% end %>
            <% end %>
          </tr>
        </table>
        <div class="select_box_list">
          <table>
            <col width="30%"/>
            <col width="30%"/>
            <col width="15%"/>
            <col width="15%"/>
            <col width="12%"/>

            <tr style="font-weight: bold">
              <td>
              Client<%= order_jobs_tasks_helper("j","client") %>
              </td>
              <td>
                Job<%= order_jobs_tasks_helper("j","job") %>
              </td>
              <td>
                Start date<%= order_jobs_tasks_helper("j","start_date") %>
              </td>
              <td>
                End date<%= order_jobs_tasks_helper("j","end_date") %>
              </td>
              <td>
                Progress<%= order_jobs_tasks_helper("j","progress") %>
              </td>
            </tr>

            <% if @myuser %>
              <% @myuser.jobs_for_myuser.each do |job| %>
                <tr>
                  <td>
                    <%= job.client.name %>
                  </td>
                  <td>
                    <%= link_to job.name, edit_job_path(job) %>
                  </td>
                  <td>
                    <%= job.start_date %>
                  </td>
                  <td>
                    <%= job.end_date %>
                  </td>
                  <td>
                    <% if job.on_schedule %>
                    <span style="color: green">ok</span>
                    <% else %>
                    <span style="color: red">?</span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>

          </table>

        </div>
      </div>


      <div class="select_box_wrapper" style="height: 174px; margin-top: 4px; background-color: lightblue; ">
        <table>
          <col width="31%">
          <col width="30%">
          <col width="13%">
          <col width="13%">
          <col width="13%">
          <tr>
            <td>
              <span style="font-weight: bold">Your tasks</span>
            </td>
            <% if @myuser %>
              <td>
                Include if associated by:
              </td>
              <%= form_tag homepage_tasks_include_path,  :id => 'tasks_include' do %>
                <td>
                  Clients <%= check_box_tag 'tasks_include_clients', 1, @myuser.show_tasks_by_client, onchange: "tasks_include.submit()" %>
                </td>
                <td>
                  Jobs <%= check_box_tag 'tasks_include_jobs', 1, @myuser.show_tasks_by_job, onchange: "tasks_include.submit()" %>
                </td>
                <td>
                  Tasks <%= check_box_tag 'tasks_include_tasks', 1, @myuser.show_tasks_by_task, onchange: "tasks_include.submit()" %>
                </td>
              <% end %>
            <% end %>
          </tr>
        </table>
        <div class="select_box_list">
          <table>
            <col width="14%"/>
            <col width="18%"/>
            <col width="20%"/>
            <col width="15%"/>
            <col width="15%"/>
            <col width="18%"/>

            <tr style="font-weight: bold">
              <td>
                Client<%= order_jobs_tasks_helper("t","client") %>
              </td>
              <td>
                Job<%= order_jobs_tasks_helper("t","job") %>
              </td>

              <td>
                Task<%= order_jobs_tasks_helper("t","task") %>
              </td>
              <td>
                Start date<%= order_jobs_tasks_helper("t","start_date") %>
              </td>
              <td>
                End date<%= order_jobs_tasks_helper("t","end_date`") %>
              </td>
              <td>
                  Progress<%= order_jobs_tasks_helper("t","progress") %>
              </td>
            </tr>
              <% if @myuser %>
                <% @myuser.tasks_for_myuser.each do |task| %>
                  <tr>

                    <td><%=  link_to task.job.client.name, edit_client_path(task.job.client) %></td>
                    <td><%=  link_to task.job.name, edit_job_path(task.job) %></td>
                    <td><%=  link_to task.name, edit_task_path(task) %><%= task.id.to_s %></td>
                    <td style="color: red"><%=  task.start_date.strftime("%e %b %Y") %></td>
                    <td style="color: red"><%=  task.end_date.strftime("%e %b %Y") %></td>
                    <td>
                      <canvas id="myCanvas<%= task.id.to_s %>" width="70" height="10" style="border:1px solid #000000; background-color:white; "></canvas>
                      <% p = task.percentage_completed - task.est_progress * 100  %>
                      <% if p > 0 %>
                        <span style="color: green; font-size: 10px">
                        +<%= number_to_percentage(p , precision: 0) %>
                      <% elsif p == 0 %>
                        <span style="color: black; font-size: 10px">
                        ==
                      <% else %>
                      <span style="color: red; font-size: 10px">
                      <%= number_to_percentage(p , precision: 0) %>
                      <% end %>
                      </span>
                    </td>
                  </tr>
                <% end %>
              <% end %>
          </table>

        </div>
      </div>
      <div class="select_box_wrapper" style="margin-top: 4px; background-color: orange; ">
        <span style="font-weight: bold">Your clients</span><br/>
          <% if @myuser %>
            <% @myuser.clients.each do |client|%>
              <%= link_to client.name, client_path(client) %>
            <% end %>
          <% end %>

        <div class="select_box_list">
        </div>
      </div>

    </td>
  </tr>
</table>

app/views/homepage/mobile_homepage.html.erb
<table>
  <col width="100%"/>
  <tr>
    <td>
      Matters you are supervising
      <div class="select_box_wrapper" style="margin-top: 4px; background-color: lightgreen; ">
        <span style="font-weight: bold">Your clients</span>

        <div class="select_box_list">
        </div>
      </div>

    </td>
  </tr>
  <tr>
    <td>
      Message forums
      <div class="select_box_wrapper" style="margin-top: 4px; background-color: yellow; ">
        <span style="font-weight: bold">Your clients</span>

        <div class="select_box_list">
        </div>
      </div>

    </td>
  </tr>
</table>

app/views/homepage/test.html.erb
Test