config/routes.rb
Rails.application.routes.draw do

  resources :updates
  root 'homepage#homepage'
  #devise_for :users

  get 'test1' => 'user_setup#test1', as: :test1
  get 'test2' => 'user_setup#test2', as: :test2
  post 'cheat_log_in' => 'myusers#cheat_log_in', as: :cheat_log_in
  get 'reset_to_two_users'=> 'user_setup#reset_to_two_users', as: :reset_to_two_users
  get 'add_jobs_and_tasks'=> 'user_setup#add_jobs_and_tasks', as: :add_jobs_and_tasks

  get 'set_up_clients'=> 'user_setup#set_up_clients', as: :set_up_clients

  get 'hide_jobs'=> 'homepage#hide_jobs', as: :hide_jobs
  post 'hide_selected_jobs'=> 'homepage#hide_selected_jobs', as: :hide_selected_jobs
  post 'unhide_selected_jobs'=> 'homepage#unhide_selected_jobs', as: :unhide_selected_jobs
  get 'order_jobs_tasks'=> 'homepage#order_jobs_tasks', as: :order_jobs_tasks

  get 'hide_tasks'=> 'homepage#hide_tasks', as: :hide_tasks
  post 'hide_selected_tasks'=> 'homepage#hide_selected_tasks', as: :hide_selected_tasks
  post 'unhide_selected_tasks'=> 'homepage#unhide_selected_tasks', as: :unhide_selected_tasks

  get 'task_log/.:id'=> 'tasks#task_log', as: :task_log

  get 'new_user' => 'myusers#new_user' , as:  :new_user

  get 'tasks/message_forum/.:id' => 'tasks#message_forum', as: :tasks_message_forum
  get 'jobs/message_forum/.:id' => 'jobs#message_forum', as: :jobs_message_forum
  post 'task_summons_email/.:id' => 'tasks#summons_email', as: :task_summons_email
  post 'job_summons_email/.:id' => 'jobs#summons_email', as: :job_summons_email
  get 'tasks/summons_landing/.:id' => 'tasks#summons_landing', as: :summons_landing

  post 'jobs_selection' => 'homepage#jobs_include', as: :homepage_jobs_include
  post 'tasks_selection' => 'homepage#tasks_include', as: :homepage_tasks_include

  post 'amend_comments_for_update/.:id' => 'updates#amend_comments_for_update', as: :amend_comments_for_update
  post 'amend_progress_for_update/.:id' => 'updates#amend_progress_for_update', as: :amend_progress_for_update
  post 'amend_comments_for_log/.:id' => 'tasks#amend_comments_for_log', as: :amend_comments_for_log

  #get 'myusers.:id' => 'user_setup#new_user_resend_email'
  #post 'myusers' => 'user_setup#new_user_details'
  #patch 'myusers.:id', :to => 'user_setup#new_user_confirm_details', :as => :myuser

  get 'myuser/confirmation' => 'myusers#new_user_confirmation'
  get 'myuser/invited_user_show/.:id' => 'myusers#invited_user_show', as: :invited_user_show
  patch 'myuser/update_invited_myuser/.:id' => 'myusers#update_invited_user', as: :update_invited_user
  patch 'myuser/myuser_amend/.:id' => 'myusers#myuser_amend', as: :myuser_amend
  #patch 'myuser/update_user/.:id' => 'myusers#update_user', as: :update_user

  post 'myuser/user_invite_return/.:id' => 'myusers#user_invite_return', as: :user_invite_return
  post 'myuser/confirm_for_new_admin_user' => 'myusers#confirm_for_new_admin_user', as: :confirm_for_new_admin_user

  post 'myusers/search' => 'myusers#search', as:  :myusers_search

  get 'login' => 'myusers#login', as:  :login
  post 'login_submit' => 'myusers#login_submit', as:  :login_submit
  delete 'logout' => 'myusers#logout', as: :logout

  #get 'jobs.:clientid' => 'jobs#index_for_client'
  #get 'jobs/new.:clientid' => 'jobs#new'
  post 'clients/client_users/.:id', to:  "clients#client_users" , as:  :client_users
  post 'clients/search', to:  "clients#search" , as:  :clients_search

  get 'clients/show_with_all_fes/.:id', to:  "clients#show_with_all_fes" , as:  :show_with_all_fes


  get 'client/newcontact/.:id', to:  "contacts#new_contact_for_client" , as:  :new_contact_for_client
  get 'client/newjob/.:id', to:  "jobs#new_job_for_client" , as:  :new_job_for_client
  post 'upload_user_file', to:  "myusers#upload_user_file" , as:  :upload_user_file
  post 'import_users', to:  "myusers#import_users" , as:  :import_users
  get 'edit_temp_user/.:id', to:  "myusers#edit_temp_user" , as:  :edit_temp_user
  post 'temp_user/.:id', to:  "myusers#update_temp_user" , as:  :temp_user
  get 'list_temp_users', to:  "myusers#list_temp_users" , as:  :list_temp_users
  delete 'delete_selected_users', to:  "myusers#delete_selected_users" , as:  :delete_selected_users

  get 'job/newtask/.:jobid', to:  "tasks#new_task_for_job" , as:  :new_task_for_job

  get 'job/amendteam/.:id', to:  "jobs#amend_team" , as:  :job_amend_team
  post 'job/addusers/.:jobid', to:  "jobs#add_users" , as:  :job_add_user
  post 'job/removeusers/.:jobid', to:  "jobs#remove_users" , as:  :job_remove_user
  post 'task/addusers/.:id', to:  "tasks#add_users" , as:  :task_add_user
  post 'task/removeusers/.:id', to:  "tasks#remove_users" , as:  :task_remove_user

  post 'job/timing/.:id', to:  "jobs#timing" , as:  :job_timing
  get 'job/today/.:id', to:  "jobs#today" , as:  :job_today
  get 'job/now/.:id', to:  "jobs#now" , as:  :job_now

  get 'update_reminder/new_for_task/.:taskid', to:  "update_reminders#new_for_task" , as:  :update_reminder_new_for_task
  get 'update_reminder/new_for_schedule/.:scheduleid', to:  "update_reminders#new_for_schedule" , as:  :update_reminder_new_for_schedule

  post '/update_reminders/:id', to: "update_reminders#update", as: :update_reminder_update
  post '/update_reminders_and_return/:id', to: "update_reminders#update_and_return", as: :update_reminder_update_and_return

  post 'update_reminder/delete_from_schedule/.:id', to:  "reminder_schedules#delete_reminder" , as:  :delete_reminder_from_schedule
  get 'update_reminder/delete_from_task/.:id', to:  "tasks#delete_reminder" , as:  :delete_reminder_from_task

  post 'template/delete/.:id', to:  "templates#delete_task" , as:  :delete_task_from_template

  get 'tasks/new_task_for_job/.:jobid', to:  "tasks#new_task_for_job" , as:  :task_new_for_job
  get 'tasks/new_task_for_template/.:templateid', to:  "tasks#new_task_for_template" , as:  :task_new_for_template

  post 'task/linked_flag/.:id', to:  "tasks#linked" , as:  :task_linked
  post 'task/timing/.:id', to:  "tasks#timing" , as:  :task_timing
  get 'task/.:id/edit1', to:  "tasks#edit1" , as:  :edit1_task
  post 'task/progress/.:id', to:  "tasks#progress" , as:  :task_update_progress
  post 'task/reminders_completed/.:id', to:  "tasks#reminders_completed" , as:  :task_reminders_completed
  get 'job/delete_task/.:taskid', to:  "jobs#delete_task" , as:  :job_delete_task
  get 'client/delete_job/.:jobid', to:  "clients#delete_job" , as:  :client_delete_job

  post 'job/import_template/.:id', to:  "jobs#import_template" , as:  :jobs_import_template
  get 'job/delete_all_tasks/.:id', to:  "jobs#delete_all_tasks" , as:  :jobs_delete_all_tasks
  post 'task/import_schedule/.:id', to:  "tasks#import_schedule" , as:  :tasks_import_schedule

  post 'update/progress/.:taskid', to:  "updates#update_progress" , as:  :update_progress
  get 'update/new_for_task/.:taskid', to:  "updates#new_for_task" , as:  :update_new_for_task

  get 'update/list_updates_for_task/.:taskid', to:  "updates#list_updates_for_task" , as:  :list_updates_for_task
  #get 'clients' => 'jobs#index_for_client'

  post 'action_update' => 'tasks#action_update', as: :action_update
  post 'action/.:message_id' => 'tasks#action', as: :action
  post 'action_delete/.:action_id' => 'tasks#action_delete', as: :action_delete


  get 'cannot_access' => 'general#cannot_access', as: :cannot_access


    resources :clients
  resources :jobs
  resources :myusers
  resources :templates
  resources :reminder_schedules
  resources :update_reminders
  resources :tasks
  resources :contacts

  #devise_scope :user do
   # get 'users/confirmation' => 'users/registrations#email_confirm'
   # post 'users/email_conf/:userid' => 'users/registrations#email_sign_in'
   # patch 'users/email_conf/:userid' => 'users/registrations#email_sign_in'
  #end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => "/cable"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :job, optional: true
  belongs_to :template, optional: true
  has_and_belongs_to_many :myusers
  has_many :task_logs
  has_many :update_reminders
  has_many :updates



  def start_date_timestg
    self.job.check_if_timezone_exists_and_valid
    if  self.job.daily_flag
      date_stg(self.start_date.in_time_zone(self.job.time_zone))
    else
      date_time_stg(self.start_date.in_time_zone(self.job.time_zone))
    end
  end

  def set_up_new_task

    self.name = "New task"
    self.linked_flag = false
    self.link_to_start = true
    self.offset = 0
    self.duration = 7
    self.completed_flag = false
    self.percentage_completed = 0.0
    self.bespoke_offset_flag = false
    self.bespoke_duration_flag = false
    self.fixed_end_date = false

    self.start_date = Date.today
    self.end_date = Date.today + self.duration.to_i.days

  end

  def end_date_timestg
    self.job.check_if_timezone_exists_and_valid
    if !self.end_date.blank?
      if  self.job.daily_flag
        date_stg(self.end_date.in_time_zone(self.job.time_zone))
      else
        date_time_stg(self.end_date.in_time_zone(self.job.time_zone))
      end
    end
  end

  def date_stg(date_value)
    if date_value.blank?
      ""
    else
      date_value.strftime("%a, %d %b %Y")
    end
  end

  def myuser_can_edit(myuser)
    self.job.client.myuser_is_superviser(myuser) || self.job.myusers.include?(myuser)
  end

  def myuser_can_view(myuser)
    self.myuser_can_edit(myuser) || self.myusers.include?(myuser)
  end

  def date_time_stg(date_value)
    if date_value.blank?
      ""
    else
      date_value.strftime("%a, %e %b %Y %H:%M")
    end
  end

  def duration_to_s
    if self.duration.to_i == self.duration
      self.duration.to_i.to_s
    else
      self.duration.to_s
    end
  end

  def parse_date(date_hash)
    begin
      if !date_hash.blank?
        if self.job.daily_flag
          Date.new( date_hash["(1i)"].to_i, date_hash["(2i)"].to_i, date_hash["(3i)"].to_i )
        else
          DateTime.new( date_hash["(1i)"].to_i, date_hash["(2i)"].to_i, date_hash["(3i)"].to_i, date_hash["(4i)"].to_i, date_hash["(5i)"].to_i,0 )
        end
      end
    rescue
      Date.new(date_hash["(1i)"].to_i, date_hash["(2i)"].to_i, 1 )

    end
  end

  def duration_is_days
    self.job.daily_flag | self.duration_in_days
  end

  def est_progress
    if !self.job.blank? && !self.start_date.blank? && !self.end_date.blank?
      (( Time.now.in_time_zone(self.job.time_zone) - self.start_date.in_time_zone(self.job.time_zone) ) / (self.end_date.in_time_zone(self.job.time_zone) - self.start_date.in_time_zone(self.job.time_zone))).clamp(0,1)
    else
      0
    end
  end

  def task_update_array_entry
    "{task: " + self.id.to_s + ", exp_prog: " + self.est_progress.to_s + ", act_prog:" + (self.percentage_completed / 100).to_s + "}"
  end

  def next_update
    #input info
    #current time; start date of task; end date of task; date of last update


    if Update.where(task_id: self.id).count > 0 && Update.where(task_id: self.id).order(:created_at).last.percentage_completed == 100
      nil
    else
      time_for_reminder = nil
      next_reminder = nil

      self.update_reminders.each do |reminder|
        t = reminder.get_next_reminder_date
        if !t.blank?
          if (time_for_reminder.blank? || t < time_for_reminder) && !(self.updates.count > 0 && self.updates.order(:created_at).last.created_at >= t)
            time_for_reminder = t
            next_reminder = reminder
          end
        end
      end
      puts "***time_for_reminder+++" + time_for_reminder.to_s

      if !time_for_reminder.blank?
        { :date => time_for_reminder , :reminder => next_reminder }
      else
        puts "***nil+++"
        nil
      end
    end
  end

  def next_update_stg
    t = self.next_update
    if t.blank?
      "None"
    else
      t[:date].to_s(:day_date_time_at)
    end
  end

  def link_text
    if self.linked_flag
      if self.linked_to_task_id ==0
        "Linked to: " + self.offset_stg + " start of job"
      elsif Task.where(:id => self.linked_to_task_id).count != 0
        "Linked to: " + self.offset_stg + (self.link_to_start ? "start of: " : "end of: ") + Task.find(self.linked_to_task_id).name
      else
        ""
      end
    else
      "Fixed start date"
    end
  end

  def offset_stg

    if self.offset_in_days
      day_hour = "day(s)"
    else
      day_hour = "hour(s)"
    end

    if self.offset < 0
      self.offset.abs.to_s + " " + day_hour + " before "
    elsif offset > 0
      self.offset.abs.to_s + " " + day_hour + " days after "
    else
      ""
    end

  end

  def duration_text
    if self.fixed_end_date
      "Fixed end date"
    else
     "Duration: " +  self.duration.to_s + (self.duration_in_days ? " day(s)" : " hour(s)")
   end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<table>
  <col width="33%">
  <col width="33%">
  <col width="33%">
  <tr>
    <td>
        <span class="page_heading">
          Configure task<br/><br/>
        </span>
      <span class="heading1">
          Client: <%= link_to @client.name, client_path(@client) %><br/>
          Job: <%= link_to @job.name , job_path(@job) %><br/>
          Task: <%= link_to @task.name , job_path(@job) %><br/><br/>
        </span>

      <%= form_tag task_remove_user_path(@job),  :id => 'remove_users' do %>
        <div class="select_box_wrapper" style="height: 140px; background-color: lightpink">
          <span class="heading2">Fee-earners for this task</span>
          <br/>
          <div class="select_box_list" style="height: 100px">
            <% if @taskmyusers%>

              <% @jobmyusers.each do |myuser| %>
                <span style="white-space: nowrap;">
                  <%=check_box_tag 'check'+myuser.id.to_s %>
                  <%= link_to myuser.first_name + " " + myuser.last_name, myuser_path(myuser) %>
                </span>
              <% end %>

            <% end %>
          </div>
          <div style="align-items: right">
            <input type="submit" value="Remove fee-earners" form='remove_users' style="margin-top: 4px">
          </div>
        </div>
      <% end %>

      <%= form_tag task_add_user_path(@task),  :id => 'remove_users' do %>
        <div class="select_box_wrapper" style="height: 140px; background-color: lightpink">
          <span class="heading2">Other fee-earners for this job</span>
          <br/>
          <div class="select_box_list" style="height: 100px">
            <% if @taskmyusers%>

              <% @jobmyusers.each do |myuser| %>
                <span style="white-space: nowrap;">
                  <%=check_box_tag 'check'+myuser.id.to_s %>
                  <%= link_to myuser.first_name + " " + myuser.last_name, myuser_path(myuser) %>
                </span>
              <% end %>

            <% end %>
          </div>
          <div style="align-items: right">
            <input type="submit" value="Add fee-earners" form='remove_users' style="margin-top: 4px">
          </div>
        </div>
      <% end %>

    </td>

  </tr>
</table>

<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <%= form.hidden_field :job_id %>
  <%= form.hidden_field :task_id %>

  <div class="field">
    <%= form.label :linked_flag %>
    <%= form.check_box :linked_flag %>
  </div>

  <div class="field">
    <%= form.label :start_end_flag %>
    <%= form.check_box :start_end_flag %>
  </div>

  <div class="field">
    <%= form.label :offset %>
    <%= form.text_field :offset %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="field">
    <%= form.label :completed_flag %>
    <%= form.check_box :completed_flag %>
  </div>

  <div class="field">
    <%= form.label :percentage_completed %>
    <%= form.text_field :percentage_completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_message_summons_avail_email.html.erb
Dear [FIRST_NAME]

We are seeking to undertake a project plan for the matter:

<%= job.name %>

for the client: <%= job.client.name %>

This matter is likely to run from <%= job.start_date %> to <%= job.end_date %>.  We need to know the availability of [RECIPIENT] for this period.

Please join the message forum by clicking below and provide the details.

[LINK]

Many thanks

<%= sending_user.name %>

app/views/tasks/_message_summons_email.html.erb
Dear [FIRST_NAME]

We are having an online forum discussion regarding:

<% if !task.blank? %><%= task.name %>;

for the client:

<%= task.job.client.name %>.<% elsif !job.blank? %><%= job.name %>

for the client: <%= job.client.name %>.<% end %>

If you are available, could you please join us by clicking here.

[LINK]

Many thanks

<%= sending_user.name %>

app/views/tasks/edit_for_template.html.erb
<span class="page_heading">
  Configure task for template: <%= @template.name %>
</span>
<%= form_for @task do |f| %>
  Name <%= f.text_field :name , :style => "margin-top: 10px; margin-bottom: 10px; width: 350px; height:30px" %>
  <%= f.submit "OK" %>
<% end %>
<table>
  <tr>
    <td>
      <div class="select_box_wrapper" style="height: 140px; background-color: yellow">
        <span class="heading2">Timetabling</span>

        <%= form_tag task_timing_path(@task), :id => 'timing_form' do %>

            Link to:
            <%= select_tag "linked_to_task", options_for_select(@tasks_to_link_to, @task.linked_to_task_id) , {:style => "width:250px;"} %>

            Start<%= raw( radio_button_tag :start_end, 1, @task.link_to_start) %>
            End<%= raw( radio_button_tag :start_end, 0, !@task.link_to_start ) %>

            Offset
            <span style="position: relative; top: 0; left: 0;" >
            <% if @task.bespoke_offset_flag %>>
                <%= text_field_tag "offset_days_text", @task.offset.to_i ,{:style => "width:74px;  text-align: right; position: absolute; top: -2px; left: -2px; background: lightblue;"}  %>
            <% end %>
              <%= select_tag "offset_days_select", options_for_select(@offset_options , offset_days_value(@task) ) , {:style => "width:80px;  text-align-last:right;", :onchange => raw("timing_form.submit()")}%>
              days
            </span>
            <% if !@template.daily_flag %>
              <%= select_tag "offset_hours", options_for_select(@offset_options_hours, offset_duration_hours_value(@task.offset)), {:style => "width:80px;  text-align-last:right;" }%>
              hours
            <% end %>


          <br/>
          <br/>

          Specify duration
          <span style="position: relative; top: 0; left: 0;" >
              <% if @task.bespoke_duration_flag %>>
              <%= text_field_tag "duration_days_text", @task.duration.to_i ,{:style => "width:44px;  text-align: right; position: absolute; top: -2px; left: -2px; background: lightblue;"}  %>
              <% end %>
            <%= select_tag "duration_days_select", options_for_select(@duration_options, duration_days_value(@task)) , {:style => "width:50px;  text-align-last:right;", :onchange => raw("timing_form.submit()")}%>
            days
            </span>

            <% if !@template.daily_flag %>
              <%= select_tag "duration_hours", options_for_select(@duration_options_hours, offset_duration_hours_value(@task.duration)), {:style => "width:80px;  text-align-last:right;" }%>
              hours
            <% end %>

          <br/>
          <div style="margin-top: 6px">
            <%= submit_tag "OK" %>
          </div>
        <% end %>



      </div>

      <div class="select_box_wrapper" style="height: 140px; background-color: lightblue; margin-top: 14px">
        <table>
          <tr>
            <td>
              <span class="heading2">Update schedule</span><br/>
              <div class="select_box_list" style="height: 100px">
                <table>
                  <col width="2%">
                  <col width="40%">
                  <col width="58%">
                  <% @task.update_reminders.each do |update_reminder| %>
                    <tr>
                      <td></td>
                      <td>
                        <%= link_to update_reminder.reminder_text, edit_update_reminder_path(update_reminder) , :method => :get  %>
                      </td>
                      <td>
                        <%= link_to "Delete", delete_reminder_from_task_path(update_reminder) , :method => :post  %>


                      </td>
                    </tr>
                  <% end %>
                </table>
              </div>
              <%= button_to "Add new reminder", update_reminder_new_for_task_path(@task), :method => "get" %>
            </td>
          </tr></table>
      </div>


    </td>



  </tr>
</table>

<%= button_to "Back to template", edit_template_path(@template), :method => "get" , :style => "margin-top: 10px; margin-left: 20px; width: 150px; height:30px"%>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Job</th>
      <th>Task</th>
      <th>Linked flag</th>
      <th>Start end flag</th>
      <th>Offset</th>
      <th>Duration</th>
      <th>Completed flag</th>
      <th>Percentage completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= task.job_id %></td>
        <td><%= task.task_id %></td>
        <td><%= task.linked_flag %></td>
        <td><%= task.start_end_flag %></td>
        <td><%= task.offset %></td>
        <td><%= task.duration %></td>
        <td><%= task.completed_flag %></td>
        <td><%= task.percentage_completed %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

Client <%= @client.name %> <br/>
Job: <%= @job.name %> <br/>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<p>
  <strong>Job:</strong>
  <%= @task.job_id %>
</p>

<p>
  <strong>Task:</strong>
  <%= @task.task_id %>
</p>

<p>
  <strong>Linked flag:</strong>
  <%= @task.linked_flag %>
</p>

<p>
  <strong>Start end flag:</strong>
  <%= @task.start_end_flag %>
</p>

<p>
  <strong>Offset:</strong>
  <%= @task.offset %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @task.duration %>
</p>

<p>
  <strong>Completed flag:</strong>
  <%= @task.completed_flag %>
</p>

<p>
  <strong>Percentage completed:</strong>
  <%= @task.percentage_completed %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/summons_email_sent.html.erb
<div class="heading1" style="margin-top: 50px"> Summons email sent</div>
<br/>
<br/>
<%= button_to "Return to forum" , tasks_message_forum_path(@task),   {:method => :get , :class=>"large_button" } %>

app/views/tasks/summons_landing.html.erb
<table>
  <col width="20%"" />
  <col width="80%"" />
  <tr>
    <td></td>
    <td>
      <div class="heading1">Welcome to Law OnTime
      <br/>

      <div style="margin-top: 30px">
        Please click below here to move you your forum
      </div>

      </div>

      <button class="large_button" style="margin-top: 30px" onclick="window.open('<%= tasks_message_forum_path(@task)%>', 'MsgWindow', 'width=400,height=500,left=400,top=100,location=0,status=0,titlebar=0,toolbar=0,menu=0');" >Message forum</bu
    </td>
  </tr>
</table>

app/views/tasks/task_log.html.erb
<span class="page_heading">
  Log of changes to task timing
</span>
  <br/>
  <div class="select_box_wrapper" style="height: 30px; margin-top: 10px; background-color: lightpink">
    <table>
      <col width="20%"/>
      <col width="40%"/>
      <col width="40%"/>
      <tr>
        <td>
          <span style="font-weight:bold">Client: </span><%= link_to @task.job.client.name, client_path(@task.job.client) %><br/>
        </td>
        <td>
          <span style="font-weight:bold">Job: </span><%= link_to @task.job.name , edit_job_path(@task.job) %><br/>
        </td>
        <td>
          <span style="font-weight:bold">Task: </span><%= link_to @task.name , edit_task_path(@task) %><br/>
        <td>
      </tr>
    </table>
  </div>

<div class="select_box_wrapper" style="height: 350px; margin-top: 10px; background-color: yellow">
  <div class="select_box_list" style="height: 350px">
  <table>
    <col width="14%"/>
    <col width="16%"/>
    <col width="19%"/>
    <col width="17%"/>
    <col width="20%"/>
    <col width="4%"/>
    <tr style="font-weight: bold">
      <td>Date/time</td>
      <td>User making change</td>
      <td>Change</td>
      <td></td>
      <td>Comments</td>

    </tr>

      <% logs = @task.task_logs.order('created_at DESC') %>
      <% logs.each do |log| %>
        <tr>
          <td><%= log.created_at.to_s(:date_time_at) %> </td>
          <td>
            <%= log.myuser.name %>
          </td>
            <% if log == logs.last %>
              <td>
              </td>
              <td>
              </td>
            <% else %>
              <td>
                <% old_log = @task.task_logs.where("created_at < ?", log.created_at).order('created_at ASC').last %>
                Old <%= old_log.start_date.to_s %>
                New <%= log.start_date.to_s %> 
                <%= log.changes_to_linking_stg ( old_log ) %>
              </td>
              <td>
                <%= log.changes_to_dates_stg ( old_log ) %>
              </td>
              <% if logged_in_user_helper == log.myuser %>
                <%= form_tag amend_comments_for_log_path(log) do %>
                  <td>
                    <%= text_area_tag :comments, log.comments, style: "width:97%; height: 40px" %>
                  </td>
                  <td>
                    <%= submit_tag "Update" , class: "messages_button"  %>
                  </td>
                <% end %>
              <% else %>
                <td>
                  <%= log.comments %>
                </td>
                <td>
                </td>
              <% end %>


            <% end %>
        </tr>
      <% end %>


  </table>
  </div>
</div>