config/routes.rb
Rails.application.routes.draw do

  resources :updates
  root 'homepage#homepage'
  #devise_for :users

  get 'test1' => 'user_setup#test1', as: :test1
  get 'test2' => 'user_setup#test2', as: :test2
  post 'cheat_log_in' => 'myusers#cheat_log_in', as: :cheat_log_in
  get 'reset_to_two_users'=> 'user_setup#reset_to_two_users', as: :reset_to_two_users
  get 'add_jobs_and_tasks'=> 'user_setup#add_jobs_and_tasks', as: :add_jobs_and_tasks

  get 'set_up_clients'=> 'user_setup#set_up_clients', as: :set_up_clients

  get 'hide_jobs'=> 'homepage#hide_jobs', as: :hide_jobs
  post 'hide_selected_jobs'=> 'homepage#hide_selected_jobs', as: :hide_selected_jobs
  post 'unhide_selected_jobs'=> 'homepage#unhide_selected_jobs', as: :unhide_selected_jobs
  get 'order_jobs_tasks'=> 'homepage#order_jobs_tasks', as: :order_jobs_tasks

  get 'hide_tasks'=> 'homepage#hide_tasks', as: :hide_tasks
  post 'hide_selected_tasks'=> 'homepage#hide_selected_tasks', as: :hide_selected_tasks
  post 'unhide_selected_tasks'=> 'homepage#unhide_selected_tasks', as: :unhide_selected_tasks

  get 'task_log/.:id'=> 'tasks#task_log', as: :task_log

  get 'new_user' => 'myusers#new_user' , as:  :new_user

  get 'tasks/message_forum/.:id' => 'tasks#message_forum', as: :tasks_message_forum
  get 'jobs/message_forum/.:id' => 'jobs#message_forum', as: :jobs_message_forum
  post 'task_summons_email/.:id' => 'tasks#summons_email', as: :task_summons_email
  post 'job_summons_email/.:id' => 'jobs#summons_email', as: :job_summons_email
  get 'tasks/summons_landing/.:id' => 'tasks#summons_landing', as: :summons_landing

  post 'jobs_selection' => 'homepage#jobs_include', as: :homepage_jobs_include
  post 'tasks_selection' => 'homepage#tasks_include', as: :homepage_tasks_include

  post 'amend_comments_for_update/.:id' => 'updates#amend_comments_for_update', as: :amend_comments_for_update
  post 'amend_progress_for_update/.:id' => 'updates#amend_progress_for_update', as: :amend_progress_for_update
  post 'amend_comments_for_log/.:id' => 'tasks#amend_comments_for_log', as: :amend_comments_for_log

  #get 'myusers.:id' => 'user_setup#new_user_resend_email'
  #post 'myusers' => 'user_setup#new_user_details'
  #patch 'myusers.:id', :to => 'user_setup#new_user_confirm_details', :as => :myuser

  get 'myuser/confirmation' => 'myusers#new_user_confirmation'
  get 'myuser/invited_user_show/.:id' => 'myusers#invited_user_show', as: :invited_user_show
  patch 'myuser/update_invited_myuser/.:id' => 'myusers#update_invited_user', as: :update_invited_user
  patch 'myuser/myuser_amend/.:id' => 'myusers#myuser_amend', as: :myuser_amend
  #patch 'myuser/update_user/.:id' => 'myusers#update_user', as: :update_user

  post 'myuser/user_invite_return/.:id' => 'myusers#user_invite_return', as: :user_invite_return
  post 'myuser/confirm_for_new_admin_user' => 'myusers#confirm_for_new_admin_user', as: :confirm_for_new_admin_user

  post 'myusers/search' => 'myusers#search', as:  :myusers_search

  get 'login' => 'myusers#login', as:  :login
  post 'login_submit' => 'myusers#login_submit', as:  :login_submit
  delete 'logout' => 'myusers#logout', as: :logout

  #get 'jobs.:clientid' => 'jobs#index_for_client'
  #get 'jobs/new.:clientid' => 'jobs#new'
  post 'clients/client_users/.:id', to:  "clients#client_users" , as:  :client_users
  post 'clients/search', to:  "clients#search" , as:  :clients_search

  get 'clients/show_with_all_fes/.:id', to:  "clients#show_with_all_fes" , as:  :show_with_all_fes


  get 'client/newcontact/.:id', to:  "contacts#new_contact_for_client" , as:  :new_contact_for_client
  get 'client/newjob/.:id', to:  "jobs#new_job_for_client" , as:  :new_job_for_client
  post 'upload_user_file', to:  "myusers#upload_user_file" , as:  :upload_user_file
  post 'import_users', to:  "myusers#import_users" , as:  :import_users
  get 'edit_temp_user/.:id', to:  "myusers#edit_temp_user" , as:  :edit_temp_user
  post 'temp_user/.:id', to:  "myusers#update_temp_user" , as:  :temp_user
  get 'list_temp_users', to:  "myusers#list_temp_users" , as:  :list_temp_users
  delete 'delete_selected_users', to:  "myusers#delete_selected_users" , as:  :delete_selected_users

  get 'job/newtask/.:jobid', to:  "tasks#new_task_for_job" , as:  :new_task_for_job

  get 'job/amendteam/.:id', to:  "jobs#amend_team" , as:  :job_amend_team
  post 'job/addusers/.:jobid', to:  "jobs#add_users" , as:  :job_add_user
  post 'job/removeusers/.:jobid', to:  "jobs#remove_users" , as:  :job_remove_user
  post 'task/addusers/.:id', to:  "tasks#add_users" , as:  :task_add_user
  post 'task/removeusers/.:id', to:  "tasks#remove_users" , as:  :task_remove_user

  post 'job/timing/.:id', to:  "jobs#timing" , as:  :job_timing
  get 'job/today/.:id', to:  "jobs#today" , as:  :job_today
  get 'job/now/.:id', to:  "jobs#now" , as:  :job_now

  get 'update_reminder/new_for_task/.:taskid', to:  "update_reminders#new_for_task" , as:  :update_reminder_new_for_task
  get 'update_reminder/new_for_schedule/.:scheduleid', to:  "update_reminders#new_for_schedule" , as:  :update_reminder_new_for_schedule

  post '/update_reminders/:id', to: "update_reminders#update", as: :update_reminder_update
  post '/update_reminders_and_return/:id', to: "update_reminders#update_and_return", as: :update_reminder_update_and_return

  post 'update_reminder/delete_from_schedule/.:id', to:  "reminder_schedules#delete_reminder" , as:  :delete_reminder_from_schedule
  get 'update_reminder/delete_from_task/.:id', to:  "tasks#delete_reminder" , as:  :delete_reminder_from_task

  post 'template/delete/.:id', to:  "templates#delete_task" , as:  :delete_task_from_template

  get 'tasks/new_task_for_job/.:jobid', to:  "tasks#new_task_for_job" , as:  :task_new_for_job
  get 'tasks/new_task_for_template/.:templateid', to:  "tasks#new_task_for_template" , as:  :task_new_for_template

  post 'task/linked_flag/.:id', to:  "tasks#linked" , as:  :task_linked
  post 'task/timing/.:id', to:  "tasks#timing" , as:  :task_timing
  get 'task/.:id/edit1', to:  "tasks#edit1" , as:  :edit1_task
  post 'task/progress/.:id', to:  "tasks#progress" , as:  :task_update_progress
  post 'task/reminders_completed/.:id', to:  "tasks#reminders_completed" , as:  :task_reminders_completed
  get 'job/delete_task/.:taskid', to:  "jobs#delete_task" , as:  :job_delete_task
  get 'client/delete_job/.:jobid', to:  "clients#delete_job" , as:  :client_delete_job

  post 'job/import_template/.:id', to:  "jobs#import_template" , as:  :jobs_import_template
  get 'job/delete_all_tasks/.:id', to:  "jobs#delete_all_tasks" , as:  :jobs_delete_all_tasks
  post 'task/import_schedule/.:id', to:  "tasks#import_schedule" , as:  :tasks_import_schedule

  post 'update/progress/.:taskid', to:  "updates#update_progress" , as:  :update_progress
  get 'update/new_for_task/.:taskid', to:  "updates#new_for_task" , as:  :update_new_for_task

  get 'update/list_updates_for_task/.:taskid', to:  "updates#list_updates_for_task" , as:  :list_updates_for_task
  #get 'clients' => 'jobs#index_for_client'

  post 'action_update' => 'tasks#action_update', as: :action_update
  post 'action/.:message_id' => 'tasks#action', as: :action
  post 'action_delete/.:action_id' => 'tasks#action_delete', as: :action_delete


  get 'cannot_access' => 'general#cannot_access', as: :cannot_access


    resources :clients
  resources :jobs
  resources :myusers
  resources :templates
  resources :reminder_schedules
  resources :update_reminders
  resources :tasks
  resources :contacts

  #devise_scope :user do
   # get 'users/confirmation' => 'users/registrations#email_confirm'
   # post 'users/email_conf/:userid' => 'users/registrations#email_sign_in'
   # patch 'users/email_conf/:userid' => 'users/registrations#email_sign_in'
  #end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => "/cable"
end

app/controllers/jobs_controller.rb
  class JobsController < ApplicationController

    before_action :get_job, only: [:amend_team, :timing, :today, :show, :now, :edit, :update, :import_template, :delete_all_tasks, :message_forum]



  def index_for_client
    get_client
    client_id = @client.id
    @jobs = Job.where(:client => client_id)
    render 'index'
  end

  def new_job_for_client

    @job= Job.new
    @job.set_up_new_job
    get_client
    @job.client=@client
    @job.save

    setup_for_edit
    render 'edit'
  end



  def create
    @job = Job.new (job_params)
    @job.set_up_new_job
    @job.name = params[:name]
    client=Client.find(@job.client_id)
    if @job.save
      redirect_to client_path(client)
    else
      redirect_to client_path(client)
    end
  end

  def amend_team
  end

  def add_users
    job= Job.find(params[:jobid])
    myusers = Myuser.all
    myusers.each do |myuser|
      s = params['check'+myuser.id.to_s]
      if !s.blank?
        job.myusers << myuser
      end
    end
    job.save
    redirect_to edit_job_path(job)
  end

  def remove_users
    job= Job.find(params[:jobid])
    myusers = Myuser.all
    myusers.each do |myuser|
      s = params['check'+myuser.id.to_s]
      if !s.blank?
        job.myusers.delete(myuser)
      end
    end
    job.save
    redirect_to edit_job_path(job)
  end

  def timing

    time_zone = params[:time_zone]

    if !time_zone.blank?
      @job.daily_flag = (params[:daily_option] == "1")

      @job.time_zone=time_zone

      d1 = params[:start]

      if @job.daily_flag
        time_start_string = d1["(1i)"] + "/" + d1["(2i)"] + "/" + d1["(3i)"]
        @job.start = ActiveSupport::TimeZone[time_zone].parse(time_start_string)
      else
        d2 = params[:start_time]

        if !d2.blank?
          time_start_string = d1["(1i)"] + "/" + d1["(2i)"] + "/" + d1["(3i)"] + " " +  d2["(4i)"] + ":" + d2["(5i)"]
          @job.start = ActiveSupport::TimeZone[time_zone].parse(time_start_string)
        else
          time_start_string = d1["(1i)"] + "/" + d1["(2i)"] + "/" + d1["(3i)"] + " " +  Rails.configuration.working_day_start_time
          @job.start = ActiveSupport::TimeZone[time_zone].parse(time_start_string)
        end

        d=params[:working_day_start]
        if !d.blank?
          working_day_start_string = d["(4i)"] + ":" + d["(5i)"]
          @job.working_day_start = ActiveSupport::TimeZone[time_zone].parse(working_day_start_string)
        else
          @job.working_day_start = ActiveSupport::TimeZone[time_zone].parse(Rails.configuration.working_day_start_time)
        end

        d=params[:working_day_end]
        if !d.blank?
          working_day_end_string = d["(4i)"] + ":" + d["(5i)"]
          @job.working_day_end = ActiveSupport::TimeZone[time_zone].parse(working_day_end_string)
        else
          @job.working_day_end = ActiveSupport::TimeZone[time_zone].parse(Rails.configuration.working_day_end_time)
        end
      end

      @job.include_weekends = (params[:inc_weekends]=="1")



      @job.save

    end

    redirect_to edit_job_path(@job)

  end

  def show

  end

  def today
    if @job.daily_flag
      @job.start = Date.today
    else
      @job.start = Date.today + @job.start.hour*3600 + @job.start.min*60
    end
    @job.save
    redirect_to edit_job_path(@job)
  end

  def now
    if !@job.daily_flag
      @job.start = Time.now.in_time_zone(@job.time_zone)

      @job.save
    end
    redirect_to edit_job_path(@job)
  end

  def setup_for_edit
    @templates=[]
    Template.all.each do |template|
      @templates<< [template.name ,template.id ]
    end

  end

  def edit
    @job.update_timings
    setup_for_edit

  end

  def delete_task
    get_task
    @job=@task.job
    @task.delete
    @job.update_timings
    setup_for_edit
    render 'edit'

  end

  def update
    @job.update(job_params)

    redirect_to edit_job_path (@job)

  end

  def import_template
    template=Template.find(params[:template])

    lookup={}
    template.tasks.each do |task|

      new_task=Task.new
      new_task.set_up_new_task
      new_task.name=task.name
      new_task.linked_to_task_id=task.linked_to_task_id
      if new_task.linked_to_task_id.blank?
        new_task.linked_to_task_id=0
      end

      new_task.linked_flag=task.linked_flag

      new_task.offset=task.offset
      new_task.link_to_start=task.link_to_start


      new_task.bespoke_offset_flag=task.bespoke_offset_flag
      new_task.bespoke_duration_flag=task.bespoke_duration_flag
      new_task.fixed_end_date=task.fixed_end_date
      new_task.duration=task.duration

      new_task.completed_flag=false
      new_task.percentage_completed=0

      new_task.for_template_flag=false

      new_task.job = @job

      task.update_reminders.each do |reminder|
        reminder.add_reminder_to_task(new_task)
      end

      @job.myusers.each do |myuser|
        new_task.myusers << myuser
      end

      new_task.save(validate: false)

      lookup[task.id]=new_task.id
    end

    lookup.each do |old_id, new_id|
      task = Task.find(new_id)
      if task.linked_flag
        new_linked_id=lookup[task.linked_to_task_id]
        if !new_linked_id.blank?
          task.linked_to_task_id = new_linked_id
          task.save(validate: false)
        end
      end
    end

    @job.update_timings

    redirect_to edit_job_path (@job)
  end


  def delete_all_tasks

    @job.tasks.delete_all


    @job.update_timings

    redirect_to edit_job_path (@job)
  end

  def message_forum
    @message_forum_name = "job" + @job.id.to_s
    @is_task = false
    @myusers_for_message_forum = @job.myusers
    render "tasks/message_forum", :layout => "message_forum"
  end


  def summons_email1

    @job.myusers.each do |myuser|
      if params["check" + myuser.id.to_s] == "1"
        UserMailer.summons_email(params[:email_message],  myuser, @job, request.base_url.to_s).deliver_now
      end
    end

    @is_task = false
    render "summons_email_sent", :layout => "message_forum"


  end

  def summons_landing

  end

  private

  def get_job
    @job = Job.find(params[:id])
  end

  def get_task
    @task= Task.find(params[:taskid])
  end

  def get_client
    @client = Client.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:name, :comment)
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f|%>
  <%= f.hidden_field :client %><br>

  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <br>

  <%= f.label :comment %><br>
  <%= f.text_field :comment %><br>
  <br>

  <%= f.label "Start" %><br>
  <%= f.datetime_field :start %><br>
  <br>

  <%= f.label "End" %><br>
  <%= f.datetime_field :end %><br>
  <br>

  <%= f.submit %><br>

  <br>
<% end %>

app/views/jobs/amend_team.html.erb
<table width="100%">
<col width="33%">
  <col width="66%">
  <tr>
    <td >
      <span class="page_heading">
        Amend team<br/><br/>
      </span>
      <span class="heading1">
        Client: <%= link_to @job.client.name, client_path(@job.client) %><br/><br/>
        Job: <%= link_to @job.name , job_path(@job) %><br/><br/>
      </span>

      <%= form_tag job_remove_user_path(@job),  :id => 'remove_users' do %>
      <div class="select_box_wrapper" style="height: 140px; background-color: lightpink">
        <span class="heading2">The team</span>
        <br/>
        <div class="select_box_list" style="height: 100px">
          <% if @job.myusers%>

            <% @job.myusers.each do |myuser| %>
              <span style="white-space: nowrap;">
                <%=check_box_tag 'check'+myuser.id.to_s %>
                <%= link_to myuser.first_name + " " + myuser.last_name + " " + myuser.id.to_s, myuser_path(myuser) %>
              </span>
            <% end %>

          <% end %>
        </div>
        <div style="align-items: right">
          <input type="submit" value="Remove fee-earners" form='remove_users' style="margin-top: 4px">
        </div>
      <% end %>
      </div>

    </td>
    <td>

      <%= form_tag job_add_user_path(@job),  :id => 'add_client_users' do %>
        <div class="select_box_wrapper">
          <% if @job.myusers.count==0 %>
            Fee-earners associated with this client
          <% else %>
            Other fee-earners associated with this client
          <% end %>
          <div class="select_box_list">
            <% if @job.client.myusers%>
              <table width="100%">
                <col width="45%">
                <col width="15%">
                <col width="20%">
                <col width="20%">

                <% @job.client.myusers.each do |myuser| %>
                  <% if @job.myusers.where(:id => myuser.id).count == 0 %>
                    <tr>
                      <td>
                        <%=check_box_tag 'check'+myuser.id.to_s %>
                        <%= link_to myuser.first_name + " " + myuser.last_name + " " + myuser.id.to_s, myuser_path(myuser) %>
                      </td>
                      <td><%= myuser.team %></td>
                      <td><%= myuser.office %></td>
                      <td><%= myuser.position %></td>
                    </tr>
                  <% end %>
                <% end %>
              </table>
            <% end %>
          </div>
          <input type="submit" value="Add fee-earner(s)" form='add_client_users' style="margin-top: 4px">
        </div>
      <% end %>

      <%= form_tag job_add_user_path(@job),  :id => 'add_any_users' do %>
        <div class="select_box_wrapper" style="margin-top: 4px">
          Other fee-earners
          <div class="select_box_list">
            <% if @myusers%>
              <table width="100%">
                <col width="45%">
                <col width="15%">
                <col width="20%">
                <col width="20%">

                <% @myusers.each do |myuser| %>
                  <% if @job.myusers.where(:id => myuser.id).count == 0 && @job.client.myusers.where(:id => myuser.id).count == 0 %>
                    <tr>
                      <td>
                        <%=check_box_tag 'check'+myuser.id.to_s %>
                        <%= link_to myuser.first_name + " " + myuser.last_name + " " + myuser.id.to_s, myuser_path(myuser) %>
                      </td>
                      <td><%= myuser.team %></td>
                      <td><%= myuser.office %></td>
                      <td><%= myuser.position %></td>
                    </tr>
                  <% end %>
                <% end %>
              </table>
            <% end %>
          </div>
          <input type="submit" value="Add fee-earner" form='add_any_users' style="margin-top: 4px">
        </div>
      <% end %>


    </td>
  </tr>
</table>

app/views/jobs/edit.html.erb
<script type="text/javascript">

  window.onload = function() {

      var tasks_progress;
      tasks_progress = <%= @job.task_update_array %>

      tasks_progress.forEach (function(task) {
        var c = document.getElementById("myCanvas" + task["task"]);
        var ctx = c.getContext("2d");
        ctx.lineWidth = "0";
        ctx.fillStyle = "red";
        ctx.fillRect(0 , c.height * 0.05 , c.width * task["exp_prog"], c.height * 0.4);

        ctx.fillStyle = "green";
        ctx.fillRect(  0, c.height * 0.55, c.width * task["act_prog"], c.height * 0.4);

      })

    }
</script>

<table>
  <col width="53%">
  <col width="47%">
  <tr>
    <td>
      <span class="heading1" style="font-size: 18pt">
        Configure job<br/>
        Client: <%= link_to @job.client.name, client_path(@job.client) %><br/><br/>
        <%= form_for @job, :method => 'patch' do |f| %>
          <table>
            <col width="20%">
            <col width="70%">
            <tr>
              <td>
                    Job name
                </td>
              <td>
                <%= f.text_field :name , :class=> "input" ,:style => "width: 300px;"  %>          <%= f.submit "OK" , :class=> "input" %>

              </td>
            </tr>
            <tr>
              <td>
                    Comments

              </td>
              <td>
              <%= f.text_area :comments , :class=> "input" ,:style => "width: 300px; height: 100px;" %>  <br/>
              </td>
            </tr>
          </table>
        <% end %>
      </span>

    <br/>

    </td>
    <td>
      <div class="select_box_wrapper" style="height: 86px">
        <span style="font-weight: bold">The team</span>
        <br/>
        <div class="select_box_list" style="height: 45px">
          <% if @job.myusers%>

            <% @job.myusers.each do |myuser| %>
              <%= link_to myuser.first_name + " " + myuser.last_name, myuser_path(myuser) %>
            <% end %>

          <% end %>
        </div>
        <div style="align-items: right">
          <table>
            <col width="25%">
            <col width="75%">
            <tr>
              <td>
                <%= button_to "Amend team" , job_amend_team_path(@job) , :method => :get , :class=> "small_button" %>
              </td>
              <td>
                <button class="small_button" onclick="window.open('<%= jobs_message_forum_path(@job)%>', 'MsgWindow', 'width=400,height=500,left=400,top=100,location=0,status=0,titlebar=0,toolbar=0,menu=0');" >Message forum</button>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <div class="select_box_wrapper" style="height: 120px; margin-top: 4px">

        <%= form_tag job_timing_path(@job), :id => 'timing_form' do %>
        <table>
          <col width=30%/>
          <col width=70%/>
          <tr>
            <td>
              <span style="font-weight: bold">Timing</span>
            </td>
            <td style="background: lightblue">

            Time zone <%= select_tag "time_zone", options_for_select(ActiveSupport::TimeZone.all.map{|zone| [zone, zone.name]}, @job.time_zone) , {include_blank: 'Please choose' ,  onchange: "timing_form.submit();" , :class=> "input", :style => "width:150px; margin-right: 20px"} %>
          Include weekends <%=check_box_tag :inc_weekends , 1 , @job.include_weekends,  onclick: "timing_form.submit();" %>

            </td>
          </tr>
          <tr>
            <td>
              Daily<%= raw( radio_button_tag :daily_option, 1, @job.daily_flag,  onclick: "timing_form.submit();" ) %>
              Hourly<%= raw( radio_button_tag :daily_option, 0, !@job.daily_flag,  onclick: "timing_form.submit();" ) %>
            </td>
            <td style="background: lightblue">
              <% if !@job.daily_flag %>
                Working day start<%= time_select :working_day_start, "" ,
                                              {
                                                  :order => [:hour, :minute],
                                                  :default =>  @job.local_date_time(@job.working_day_start),
                                                  :minute_step => 30
                                            },
                                              {:class => "input" ,
                                              :onchange => "timing_form.submit()"} %>

               End<%= time_select :working_day_end, "" ,
                                              {
                                                  :order => [:hour, :minute],
                                                  :default => @job.local_date_time(@job.working_day_end),
                                                  :minute_step => 30
                                            },
                                              {:class => "input" ,
                                                :onchange => "timing_form.submit()"} %>
              <% end %>
            </td>
          </tr>

        </table>


        <div style="margin-top: 10px">

          Start date:
          <%= date_select :start, "" ,

                          {
                              :order => [:day, :month, :year],
                              :default => @job.local_date_time(@job.start),
                              :start_year => 2017,
                              :end_year => 2030
                          },
                          {:class=> "input",
                          :onchange => "timing_form.submit()"} %>
          <% if @job.daily_flag %>
              <%= button_to "Set to today" , job_today_path(@job) , :method => :get , :class=> "small_button", :style => "margin-right: 10px" %>
          <% end %>
          <% if !@job.daily_flag %>
          Time:
          <%= time_select :start_time, "" ,
                                          {
                                              :order => [:hour, :minute],
                                              :default => @job.local_date_time(@job.start),
                                              :minute_step => 30
                                        },
                                          {:class=> "input",
                                          :onchange => "timing_form.submit()"} %>
          <%= button_to "Set to now" , job_now_path(@job) , {:class=>"small_button", :method => :get }%>
          <% end %>
          <br/>

          <div style="color: red; margin-top: 10px">Scheduled end date: <%= @job.end_datestg %> </div>
      <% end %>
      </div>
      </div>


    </td>
  </tr>

</table>

<div class="select_box_wrapper" style="margin-top: 4px; background-color: lightblue; height: 250px;">
  <table>
    <col width="10%"/>
    <col width="90%"/>
    <tr>
      <td style="font-weight: bold">
        Tasks

      </td>
      <td>
        <%= form_tag jobs_import_template_path(@job) do %>
          Templates <%= select_tag "template", options_for_select(@templates, "") , {include_blank: 'Please choose' , :class=> "input", :style => "width:250px;"} %>
          <%= submit_tag "OK", :class=> "small_button" %>
        <% end %>

      </td>
    </tr>
  </table>
  <div class="select_box_list" style="height: 188px">
    <% if @job.tasks %>
      <table width="100%">
        <col width="15%">
        <col width="12%">
        <col width="12%">
        <col width="12%">
        <col width="25%">
        <tr style="font-weight: bold;">
          <td>
              Task name
          </td>
          <td>
            Scheduled start
          </td>
          <td>
            Scheduled end
          </td>
          <td>
            Progress
          </td>
          <td>
          </td>
        </tr>

        <% @job.tasks.each do |task| %>
          <tr>
            <td>
              <%= link_to task.name , edit_task_path(task) %>

            </td>

            <td style="color: red">
              <%= task.start_date_timestg %>
            </td>
            <td style="color: red">
              <%= task.end_date_timestg %>
            </td>
            <td>
              <canvas id="myCanvas<%= task.id.to_s %>" width="70" height="10" style="border:1px solid #000000; background-color:white; "></canvas>
              <% p = task.percentage_completed - task.est_progress * 100  %>
              <% if p > 0 %>
                <span style="color: green">
                +<%= number_to_percentage(p , precision: 0) %>
              <% elsif p == 0 %>
                <span style="color: black">
                ==
              <% else %>
              <span style="color: red">
              <%= number_to_percentage(p , precision: 0) %>
              <% end %>
              </span>
            </td>

            <td>
              <%= link_to 'Delete', job_delete_task_path(task), data: { confirm: 'Are you sure you wish to delete ' + task.name + '?' } %></td>

            </td>

          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <table>
    <col width="20%"/>
    <col width="20%"/>
    <col width="60%"/>
    <tr>
      <td>
        <%= button_to "Add task" , new_task_for_job_path(@job) , :method => :get, :class=> "small_button"%>
      </td>
      <td>
        <%= button_to "Delete all tasks" , jobs_delete_all_tasks_path(@job) , :method => :get , :class=> "small_button" %>
      </td>
      <td>

      </td>
    </tr>
  </table>


</div>

app/views/jobs/index.html.erb
Jobs for <%= @client.name %>
<br/>
<% @jobs.each do |job| %>
  <%= link_to job.name, job_path(job) %>
  <br>
<% end %>

<%= link_to "New job", new_job_path(@client) %>