config/routes.rb
Rails.application.routes.draw do

  resources :updates
  root 'homepage#homepage'
  #devise_for :users

  get 'test1' => 'user_setup#test1', as: :test1
  get 'test2' => 'user_setup#test2', as: :test2
  post 'cheat_log_in' => 'myusers#cheat_log_in', as: :cheat_log_in
  get 'reset_to_two_users'=> 'user_setup#reset_to_two_users', as: :reset_to_two_users
  get 'add_jobs_and_tasks'=> 'user_setup#add_jobs_and_tasks', as: :add_jobs_and_tasks

  get 'set_up_clients'=> 'user_setup#set_up_clients', as: :set_up_clients

  get 'hide_jobs'=> 'homepage#hide_jobs', as: :hide_jobs
  post 'hide_selected_jobs'=> 'homepage#hide_selected_jobs', as: :hide_selected_jobs
  post 'unhide_selected_jobs'=> 'homepage#unhide_selected_jobs', as: :unhide_selected_jobs
  get 'order_jobs_tasks'=> 'homepage#order_jobs_tasks', as: :order_jobs_tasks

  get 'hide_tasks'=> 'homepage#hide_tasks', as: :hide_tasks
  post 'hide_selected_tasks'=> 'homepage#hide_selected_tasks', as: :hide_selected_tasks
  post 'unhide_selected_tasks'=> 'homepage#unhide_selected_tasks', as: :unhide_selected_tasks

  get 'task_log/.:id'=> 'tasks#task_log', as: :task_log

  get 'new_user' => 'myusers#new_user' , as:  :new_user

  get 'tasks/message_forum/.:id' => 'tasks#message_forum', as: :tasks_message_forum
  get 'jobs/message_forum/.:id' => 'jobs#message_forum', as: :jobs_message_forum
  post 'task_summons_email/.:id' => 'tasks#summons_email', as: :task_summons_email
  post 'job_summons_email/.:id' => 'jobs#summons_email', as: :job_summons_email
  get 'tasks/summons_landing/.:id' => 'tasks#summons_landing', as: :summons_landing

  post 'jobs_selection' => 'homepage#jobs_include', as: :homepage_jobs_include
  post 'tasks_selection' => 'homepage#tasks_include', as: :homepage_tasks_include

  post 'amend_comments_for_update/.:id' => 'updates#amend_comments_for_update', as: :amend_comments_for_update
  post 'amend_progress_for_update/.:id' => 'updates#amend_progress_for_update', as: :amend_progress_for_update
  post 'amend_comments_for_log/.:id' => 'tasks#amend_comments_for_log', as: :amend_comments_for_log

  #get 'myusers.:id' => 'user_setup#new_user_resend_email'
  #post 'myusers' => 'user_setup#new_user_details'
  #patch 'myusers.:id', :to => 'user_setup#new_user_confirm_details', :as => :myuser

  get 'myuser/confirmation' => 'myusers#new_user_confirmation'
  get 'myuser/invited_user_show/.:id' => 'myusers#invited_user_show', as: :invited_user_show
  patch 'myuser/update_invited_myuser/.:id' => 'myusers#update_invited_user', as: :update_invited_user
  patch 'myuser/myuser_amend/.:id' => 'myusers#myuser_amend', as: :myuser_amend
  #patch 'myuser/update_user/.:id' => 'myusers#update_user', as: :update_user

  post 'myuser/user_invite_return/.:id' => 'myusers#user_invite_return', as: :user_invite_return
  post 'myuser/confirm_for_new_admin_user' => 'myusers#confirm_for_new_admin_user', as: :confirm_for_new_admin_user

  post 'myusers/search' => 'myusers#search', as:  :myusers_search

  get 'login' => 'myusers#login', as:  :login
  post 'login_submit' => 'myusers#login_submit', as:  :login_submit
  delete 'logout' => 'myusers#logout', as: :logout

  #get 'jobs.:clientid' => 'jobs#index_for_client'
  #get 'jobs/new.:clientid' => 'jobs#new'
  post 'clients/client_users/.:id', to:  "clients#client_users" , as:  :client_users
  post 'clients/search', to:  "clients#search" , as:  :clients_search

  get 'clients/show_with_all_fes/.:id', to:  "clients#show_with_all_fes" , as:  :show_with_all_fes


  get 'client/newcontact/.:id', to:  "contacts#new_contact_for_client" , as:  :new_contact_for_client
  get 'client/newjob/.:id', to:  "jobs#new_job_for_client" , as:  :new_job_for_client
  post 'upload_user_file', to:  "myusers#upload_user_file" , as:  :upload_user_file
  post 'import_users', to:  "myusers#import_users" , as:  :import_users
  get 'edit_temp_user/.:id', to:  "myusers#edit_temp_user" , as:  :edit_temp_user
  post 'temp_user/.:id', to:  "myusers#update_temp_user" , as:  :temp_user
  get 'list_temp_users', to:  "myusers#list_temp_users" , as:  :list_temp_users
  delete 'delete_selected_users', to:  "myusers#delete_selected_users" , as:  :delete_selected_users

  get 'job/newtask/.:jobid', to:  "tasks#new_task_for_job" , as:  :new_task_for_job

  get 'job/amendteam/.:id', to:  "jobs#amend_team" , as:  :job_amend_team
  post 'job/addusers/.:jobid', to:  "jobs#add_users" , as:  :job_add_user
  post 'job/removeusers/.:jobid', to:  "jobs#remove_users" , as:  :job_remove_user
  post 'task/addusers/.:id', to:  "tasks#add_users" , as:  :task_add_user
  post 'task/removeusers/.:id', to:  "tasks#remove_users" , as:  :task_remove_user

  post 'job/timing/.:id', to:  "jobs#timing" , as:  :job_timing
  get 'job/today/.:id', to:  "jobs#today" , as:  :job_today
  get 'job/now/.:id', to:  "jobs#now" , as:  :job_now

  get 'update_reminder/new_for_task/.:taskid', to:  "update_reminders#new_for_task" , as:  :update_reminder_new_for_task
  get 'update_reminder/new_for_schedule/.:scheduleid', to:  "update_reminders#new_for_schedule" , as:  :update_reminder_new_for_schedule

  post '/update_reminders/:id', to: "update_reminders#update", as: :update_reminder_update
  post '/update_reminders_and_return/:id', to: "update_reminders#update_and_return", as: :update_reminder_update_and_return

  post 'update_reminder/delete_from_schedule/.:id', to:  "reminder_schedules#delete_reminder" , as:  :delete_reminder_from_schedule
  get 'update_reminder/delete_from_task/.:id', to:  "tasks#delete_reminder" , as:  :delete_reminder_from_task

  post 'template/delete/.:id', to:  "templates#delete_task" , as:  :delete_task_from_template

  get 'tasks/new_task_for_job/.:jobid', to:  "tasks#new_task_for_job" , as:  :task_new_for_job
  get 'tasks/new_task_for_template/.:templateid', to:  "tasks#new_task_for_template" , as:  :task_new_for_template

  post 'task/linked_flag/.:id', to:  "tasks#linked" , as:  :task_linked
  post 'task/timing/.:id', to:  "tasks#timing" , as:  :task_timing
  get 'task/.:id/edit1', to:  "tasks#edit1" , as:  :edit1_task
  post 'task/progress/.:id', to:  "tasks#progress" , as:  :task_update_progress
  post 'task/reminders_completed/.:id', to:  "tasks#reminders_completed" , as:  :task_reminders_completed
  get 'job/delete_task/.:taskid', to:  "jobs#delete_task" , as:  :job_delete_task
  get 'client/delete_job/.:jobid', to:  "clients#delete_job" , as:  :client_delete_job

  post 'job/import_template/.:id', to:  "jobs#import_template" , as:  :jobs_import_template
  get 'job/delete_all_tasks/.:id', to:  "jobs#delete_all_tasks" , as:  :jobs_delete_all_tasks
  post 'task/import_schedule/.:id', to:  "tasks#import_schedule" , as:  :tasks_import_schedule

  post 'update/progress/.:taskid', to:  "updates#update_progress" , as:  :update_progress
  get 'update/new_for_task/.:taskid', to:  "updates#new_for_task" , as:  :update_new_for_task

  get 'update/list_updates_for_task/.:taskid', to:  "updates#list_updates_for_task" , as:  :list_updates_for_task
  #get 'clients' => 'jobs#index_for_client'

  post 'action_update' => 'tasks#action_update', as: :action_update
  post 'action/.:message_id' => 'tasks#action', as: :action
  post 'action_delete/.:action_id' => 'tasks#action_delete', as: :action_delete


  get 'cannot_access' => 'general#cannot_access', as: :cannot_access


    resources :clients
  resources :jobs
  resources :myusers
  resources :templates
  resources :reminder_schedules
  resources :update_reminders
  resources :tasks
  resources :contacts

  #devise_scope :user do
   # get 'users/confirmation' => 'users/registrations#email_confirm'
   # post 'users/email_conf/:userid' => 'users/registrations#email_sign_in'
   # patch 'users/email_conf/:userid' => 'users/registrations#email_sign_in'
  #end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => "/cable"
end

app/models/client.rb
class Client < ApplicationRecord
  has_and_belongs_to_many :myusers
  has_many :contacts
  has_many :jobs

  def myuser_is_superviser(myuser)
    myuser.is_admin? or Superviser.where('client_id=? AND myuser_id=?', self.id, myuser.id).count > 0
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :set_client, only: [:show, :show_with_all_fes, :edit, :update, :destroy, :add_users, :client_users]

  def index
    @clients=Client.all.order("name ASC")
  end

  def new
    @client=Client.new
  end

  def create
    @client = Client.new (client_params)
    if @client.save
      redirect_to @client
    else
      render new
    end
  end

  def edit

  end

  def update
    @client.update(client_params)
    if @client.save
      redirect_to @client
    else
      render 'edit'
    end

  end

  def show
    show1 false
  end

  def show_with_all_fes
    show1 true
  end

  def show1(flag)
    if logged_in_user_helper.is_admin? or @client.myusers.include?(logged_in_user_helper)
      @show_all_fes_flag=flag
      @myusers = Myuser.all
      @contacts = @client.contacts
      @jobs = @client.jobs

      @clientmyusers=@client.myusers
      @clients=Client.all.order("created_at DESC")
      render 'show'
    else
      redirect_to cannot_access_path
    end
  end

  def client_users

    if params[:function] == "Remove user"
      myusers = @client.myusers
      myusers.each do |myuser|
        s = params['check'+myuser.id.to_s]
        if !s.blank?
          @client.myusers.delete(myuser)
        end
      end
      @client.save
      redirect_to client_path(@client)
    elsif params[:function] == "Add user"
      myusers = Myuser.all
      myusers.each do |myuser|
        s = params['check'+myuser.id.to_s]
        if !s.blank?

          if @client.myusers.where("myuser_id=?", myuser.id).count==0 #Just to ensure not already assigned as a user

            @client.myusers << myuser
          end
        end
      end
      @client.save
      redirect_to client_path(@client)

    elsif params[:function] == "Add as super"
      myusers = @client.myusers
      myusers.each do |myuser|
        s = params['check'+myuser.id.to_s]
        if !s.blank?
          superviser=Superviser.new
          superviser.client_id=@client.id
          superviser.myuser_id=myuser.id
          superviser.save(validate: false)
        end
      end
      redirect_to client_path(@client)

    elsif params[:function] == "Remove super"

      myusers = @client.myusers
      myusers.each do |myuser|
        s = params['check'+myuser.id.to_s]
        if !s.blank?
          Superviser.where('client_id=? AND myuser_id=?', @client.id, myuser.id).delete
        end
      end
      redirect_to client_path(@client)

    elsif params[:function] == "Show other user(s)"
      redirect_to show_with_all_fes_path(@client)
    elsif params[:function] == "Hide other user(s)"
      redirect_to client_path(@client)
    end

  end

  def delete_job
    set_job
    @client=@job.client
    @job.delete
    redirect_to client_path(@client)

  end

  def search

    @clients = Myuser.all
    @search_term = params[:search]
    if !@search_term.blank?
      @clients = Client.where('name LIKE ? ', '%'+ @search_term +"%" ).order("created_at DESC")
    end

    render 'index'

  end


  private

  def set_client
    @client= Client.find(params[:id])
  end

  def set_job
    @job= Job.find(params[:jobid])
  end

  def client_params
    params.require(:client).permit(:name)
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client do |f|%>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.submit %><br>
<% end %>

app/views/clients/edit.erb
<table>
  <col width="20%"" />
  <col width="80%"" />
  <tr>
    <td></td>
    <td>
      <h1>Edit client</h1>
      <%= form_for @client do |f| %>
        <%= f.label :name , :class =>"user_text" %><br/>
        <%= f.text_field :name , :class=>"user" , :style =>"width: 550px" %><br/><br/>
        <%= f.submit :class=>"large_button" , :style =>"width: 200px" %><br/>
      <% end %>
    </td>
  </tr>
</table>

app/views/clients/index.html.erb
<span class="heading1">Clients</scan>
<div class="select_box_wrapper" style="margin-top: 4px; height: 410px; background-color: lightblue; margin-bottom: -10px">
  <div class="select_box_list" style="margin-top: 4px; height: 400px;">

    <table width="100%">
      <col width="50%">
      <col width="50%">
      <tr>
        <td>
          <%= form_tag clients_search_path , :id => 'search_form', :method => "get" do %>
            Name<%= text_field_tag :search  , @search_term , :class => "input", :style => "margin-left: 20px" %>
            <%= submit_tag 'Search' , class: "small_button" , style:  "margin-left: 5px"%>
            <% if !@search_term.blank? %>
              <%= button_to "Clear", clients_path %>
            <% end %>
          <% end %>
          </td>
        <td></td>
      </tr>
      <% @clients.each do |client| %>
        <tr>
          <td>
          <%= link_to client.name, client %>
          </td>
          <td></td>
        </tr>
      <% end %>

    </table>
  </div>
</div>
<%= button_to 'Create new client', new_client_path,  {:method => :get , :class=>"small_button" , :style => "margin-left: 10px"} %>

app/views/clients/new.html.erb
<table>
  <col width="20%"" />
  <col width="80%"" />
  <tr>
    <td></td>
    <td>
      <h1>New Client</h1>
      <%= form_for @client do |f| %>
        <%= f.label :name , :class =>"user_text" %><br/>
        <%= f.text_field :name , :class=>"user" , :style =>"width: 550px" %><br/><br/>
        <%= f.submit :class=>"large_button" , :style =>"width: 200px" %><br/>
      <% end %>
    </td>
  </tr>
</table>

app/views/clients/show.html.erb
<table style="height: 68vh;" width="100%">
  <col width="66%">
  <col width="33%">
  <tr>
    <td style="vertical-align: top;">
      <h1>Client: <%= @client.name%></h1>

      <div class="select_box_wrapper" style="margin-top: 4px; height: 400px; background-color: cyan; ">
        <span style="font-weight: bold">Jobs</span>
        <div class="select_box_list" style="margin-top: 4px; height: 354px;"">
          <% if @contacts %>
            <table width="100%">
              <col width="60%">
              <col width="40%">

              <% @jobs.each do |job| %>
                <tr>
                  <td>
                    <%= link_to job.name , edit_job_path(job) %>
                  </td>
                  <td><%= link_to 'Delete', client_delete_job_path(job), data: { confirm: 'Are you sure you wish to delete ' + job.name + '?' } %></td>

                </tr>
              <% end %>
            </table>
          <% end %>
        </div>
        <% if @client.myuser_is_superviser(logged_in_user_helper) %>
          <%= button_to "Add job" , new_job_for_client_path(@client) , :method => :get, class: "small_button" %>
        <% end %>
      </div>



    </td>
    <td >



      <%= form_tag client_users_path(@client),  :id => 'remove_supervisers' do %>
        <div class="select_box_wrapper" style="height: 100px">
          <span style="font-weight: bold">Fee-earner supervisers for this client</span>

          <br/>
          <div class="select_box_list" style="height: 61px">
            <% if @clientmyusers%>

              <table width="100%">
                <col width="45%">
                <col width="15%">
                <col width="20%">
                <col width="20%">

                <% Superviser.where('client_id=?', @client.id).uniq.each do |superviser| %>
                  <% myuser=Myuser.find(superviser.myuser_id) %>
                  <tr>
                    <td>
                      <% if @client.myuser_is_superviser(logged_in_user_helper) %>
                        <%=check_box_tag 'check'+myuser.id.to_s %>
                      <% end %>
                      <%= link_to myuser.first_name + " " + myuser.last_name, myuser_path(myuser) %>
                    </td>
                    <td><%= myuser.team %></td>
                    <td><%= myuser.office %></td>
                    <td><%= myuser.position %></td>
                  </tr>
                <% end %>

              </table>
            <% end %>
          </div>
          <% if @client.myuser_is_superviser(logged_in_user_helper) %>
            <input type="submit" name="function" value="Remove super" form='remove_supervisers' class="small_button" >
          <% end %>
        </div>

      <% end %>



      <%= form_tag client_users_path(@client),  :id => 'client_users' do %>
        <div class="select_box_wrapper" style="height: 140px; margin-top: 2px">
          <span style="font-weight: bold">Fee-earners associated with this client</span>

          <br/>
          <div class="select_box_list" style="height: 102px;">
            <% if @clientmyusers%>

              <table width="100%">
                <col width="45%">
                <col width="15%">
                <col width="20%">
                <col width="20%">

                <% @client.myusers.uniq.each do |myuser| %>
                  <% if Superviser.where('client_id =? AND myuser_id=?', @client.id, myuser.id).count==0 %>
                   <tr>
                      <td>
                        <% if @client.myuser_is_superviser(logged_in_user_helper) %>
                          <%=check_box_tag 'check'+myuser.id.to_s %>
                        <% end %>
                        <%= link_to myuser.name, myuser_path(myuser) %>
                      </td>
                      <td><%= myuser.team %></td>
                      <td><%= myuser.office %></td>
                      <td><%= myuser.position %></td>
                    </tr>
                  <% end %>
                <% end %>

              </table>
            <% end %>
          </div>
          <% if @client.myuser_is_superviser(logged_in_user_helper) %>
            <input type="submit" name="function1" value="Remove user" id="test_123" form='client_users' class="small_button"  />
            <input type="submit" name="function" value="Add as super" form='client_users' class="small_button" />

            <% if !@show_all_fes_flag %>
              <input type="submit" name="function" value="Show all" form='client_users' class="small_button"  />
            <% end %>
          <% end %>

        </div>

      <% end %>

      <% if @show_all_fes_flag %>

        <%= form_tag client_users_path(@client),  :id => 'add_users' do %>
          <div class="select_box_wrapper" style=" margin-top: 4px">
            <span style="font-weight: bold">Other fee-earners</span>

            <div class="select_box_list">
              <% if @myusers%>
                <table width="100%">
                  <col width="45%">
                  <col width="15%">
                  <col width="20%">
                  <col width="20%">

                  <% @myusers.each do |myuser| %>
                  <% if @clientmyusers.where(:id => myuser.id).count == 0 %>
                    <tr>
                      <td>
                        <% if @client.myuser_is_superviser(logged_in_user_helper) %>
                          <%=check_box_tag 'check'+myuser.id.to_s %>
                        <% end %>
                        <%= link_to myuser.first_name + " " + myuser.last_name, myuser_path(myuser) %>
                      </td>
                      <td><%= myuser.team %></td>
                      <td><%= myuser.office %></td>
                      <td><%= myuser.position %></td>
                    </tr>
                  <% end %>
                <% end %>
                </table>
              <% end %>
            </div>
            <% if @client.myuser_is_superviser(logged_in_user_helper) %>
              <input type="submit" name="function" value="Add user(s)" form='add_users' class="small_button" style="width: 180px">
              <input type="submit" name="function" value="Hide other user(s)" form='add_users'  class="small_button" style="width: 130px; background-color: lightpink; margin-top: 4px; margin-left: 14px">
            <% end %>


          </div>
        <% end %>


      <% else %>


        <div class="select_box_wrapper" style="margin-top: 2px; height: 140px;">
          <span style="font-weight: bold">Client contacts</span>

          <div class="select_box_list" style="height: 100px;">
            <% if @contacts %>
              <table width="100%">
                <col width="60%">
                <col width="40%">

                <% @contacts.each do |contact| %>
                  <tr>
                    <td>
                      <%= link_to contact.first_name + " " + contact.last_name , contact_path(contact) %>
                    </td>
                    <td><%= mail_to contact.email%></td>
                  </tr>
                <% end %>
              </table>
            <% end %>
          </div>
          <% if @client.myuser_is_superviser(logged_in_user_helper) %>
            <%= button_to "Add contacts" , new_contact_for_client_path(@client) , :method => :get , class: "small_button" %>
          <% end %>
        </div>




      <% end %>


    </td>
  </tr>
</table>

<table>
  <col width="100%">
  <tr>
    <% if @client.myuser_is_superviser(logged_in_user_helper) %>
      <%= button_to "Edit client", edit_client_path(@client),  method: :get, class: "small_button" , style: "margin-left: 10px" %>
    <% end %>

    <% if Myuser.find(session[:logged_in_user]).user_status == Rails.configuration.super_admin_name %>
      <%= button_to "Delete client", client_path(@client) , method: :delete, data: {confirm: "Are you sure?"} , class: "small_button" , style: "margin-left: 10px"  %>
    <% end %>

    <%= button_to 'Clients home page', clients_path , class: "small_button" , style: "margin-left: 10px" %>
  </tr>
</table>

app/views/clients/test.html.erb
<head>
  <style>
    .border1 {vertical-align: top; border-style: dashed;     border-color: black; border-width: 3px; border-collapse: collapse}
  </style>

</head>
<body style="height: 50%; width: 100%;">
<div class="border1" style="position: absolute; width: 70%; height: 70%">
Hi

</div>
</body>